### ISSUE TITLE
Required date field keeps failing validation even when it has a valid value

### ISSUE THREAD

**Issue by T-Roth** [deulos/vue-daval#1]
I'm having a problem validating required **date** fields

my validation rules look like this: 
`const vdRules = {
  model: {
    name: {required: true, type: 'string'},
    startDate: {required: true, type: 'date'}
  }
}
`

my simple model for testing
`  model = {
    name: 'test',
    startDate: new Date()
  }`

When I check this.$vd.model.$errors it always has an error for 'startDate' being a required field even though it has a valid date value

**Comment by deulos** [comment]
Thank man, I will review it asap and create a fix.

**Comment by deulos** [comment]
I created a new version. 2.0.1 fixing this.

Thanks for reporting!
