### ISSUE TITLE
Is there a way to use the validation without it being a mixin?

### ISSUE THREAD

**Issue by T-Roth** [deulos/vue-daval#2]
Is there a way to use the validation without it being a mixin?

**Comment by deulos** [comment]
Not by now, but I will do it in future releases

**Comment by deulos** [comment]
Hello, I was doing some tests and analyzing the behavior loading daval as plugin and I was not convinced.

Just found disadvantages and inconveniences, nothing really worth to use it as plugin so I am not implementing it. I think it would be a totally mistake and even Evan You discourages in [Vue Documentation](https://vuejs.org/v2/guide/mixins.html#Global-Mixin)

Regards and thanks anyway!
