### ISSUE TITLE
Friendly field display name in the error messages

### ISSUE THREAD

**Issue by T-Roth** [deulos/vue-daval#3]
Did the friendly field display name make it into this release?  

Thanks for your work on this project, its looking good so far.
Sorry for all the questions.

**Comment by deulos** [comment]
No problem man, feel free to ask anything, it will help others too.

About the friendly display name is already included.

Check the [Custom Messages](https://github.com/deulos/vue-daval/wiki/Custom-messages) section, You have the info there and let me know if something not clear.
