### ISSUE TITLE
Empty npm package

### ISSUE THREAD

**Issue by glutaminefree** [deulos/vue-daval#8]
I got this after running ```npm install vue-daval --save```

![Screenshot_20191118_153348](https://user-images.githubusercontent.com/2122419/69052811-fb4f6a00-0a18-11ea-8ec2-c57bb0373612.png)

Only 3 files. No dist folder or any js files.

**Comment by glutaminefree** [comment]
But ```npm install vue-daval@2.0.9 --save``` works good.

**Comment by deulos** [comment]
Hello, and thanks for reporting.

I will review it tonight.

Regards!

**Comment by deulos** [comment]
Package is fixed now with version 2.0.12

Thanks!
